name: Rekdoc
run-name: ${{ gitea.actor }}
on: [push]

jobs:
  Build:
    runs-on: linux_amd64
    steps:
      - name: Checkout Code
        run: |
          if [ "$GITEA_REF" = "refs/heads/dev" ]; then
            echo "Clonging DEV Branch"
            git clone --branch dev http://127.0.0.1:3000/rek3000/rekdoc/
          else
            echo "Clonging Origin Branch"
            git clone --branch origin http://127.0.0.1:3000/rek3000/rekdoc/
          fi

      - name: Login to Gitea Container Registry
        run: docker login -u rek3000 -p welcome1 localhost:3000
