name: Rekdoc
run-name: ${{ gitea.actor }}
on: [push]

jobs:
  Build:
    runs-on: linux_amd64
    steps:
      - name: Checkout Code
        # uses: http://127.0.0.1:3000/rek3000/checkout@v4
        run: |
          if [ "${{ gitea.ref }}" = "refs/heads/dev" ]; then
          echo "Cloning DEV Branch"
          git clone --branch dev http://127.0.0.1:3000/rek3000/rekdoc/
          else
          echo "Clonging Origin Branch"
          git clone --branch origin http://127.0.0.1:3000/rek3000/rekdoc/
          fi
      - name: Make output dir
        run: mkdir -p target/ > /dev/null 2>&1
      - name: Login to Gitea Container Registry
        run: | 
          docker login -u rek3000 -p welcome1 localhost:3000
          docker pull 127.0.0.1:3000/rek3000/rekdoc:base
      - name: Build in Docker
        run: | 
          cd rekdoc
          mkdir target
          docker build -t 127.0.0.1:3000/rek3000/rekdoc:rd -f dockerfiles/build.dockerfile .
          docker run --rm -it --mount type=bind,source="$(PWD)/target/",target="/target" \
                                                                                        --name rekdoc-gcc 127.0.0.1:3000/rek3000/rekdoc:rd /bin/bash -ci 'cp /package/dist/rd /target/'
      - name: Push to registry
        run: |
          cd rekdoc/target
          curl --user rek3000:welcome1 \
          --upload-file rd \
          http://127.0.0.1:3000/api/packages/rek3000/generic/rekdoc/1.0.0/rd




